manifest:
  remotes:
    - name: urob
      url-base: https://github.com/urob/
  projects:
    - name: zmk
      remote: urob
      revision: main
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: v2  # NOTE: this will eventually become main
  self:
    path: config
